
name: "E2E Tests on Vercel Preview"

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: 3. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: 4. Install Dependencies
        run: pnpm install

      - name: 5. Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: 6. Run Playwright Tests
        env:
          # La URL del despliegue de Vercel es inyectada automáticamente
          # por la integración de Vercel con GitHub como un "deployment status".
          # Playwright la leerá automáticamente si `playwright.config.ts` está bien configurado.
          # Como fallback, usamos una variable que Vercel provee.
          NEXT_PUBLIC_SITE_URL: ${{ steps.vercel-deployment.outputs.url }}
        run: pnpm e2e